apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: fiap-gerenciamento-pedidos-db
spec:
  containers:
    - name: db
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: db
              key: mysql.database
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: migration
  volumes:
    - name: migration
      configMap:
        name: db-migration
