apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: fiap-gerenciamento-pedidos-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-gerenciamento-pedidos-api
  template:
    metadata:
      labels:
        app: fiap-gerenciamento-pedidos-api
    spec:
      containers:
        - name: api
          image: melissa2019/api-0.0.1-snapshot:latest
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: VAL_MYSQL_HOST
            - name: MYSQL_DB
              value: VAL_MYSQL_DB
            - name: MYSQL_ROOT_USERNAME
              value: VAL_MYSQL_ROOT_USERNAME
            - name: MYSQL_ROOT_PASSWORD
              value: VAL_MYSQL_ROOT_PASSWORD
            - name: MERCADO_PAGO_USER_ID
              value: VAL_MERCADO_PAGO_USER_ID
            - name: MERCADO_PAGO_EXTERNAL_ID
              value: VAL_MERCADO_PAGO_EXTERNAL_ID
            - name: MERCADO_PAGO_TOKEN
              value: VAL_MERCADO_PAGO_TOKEN
            - name: MERCADO_PAGO_WEBHOOK_URL
              value: VAL_MERCADO_PAGO_WEBHOOK_URLb"
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
