apiVersion: v1
kind: Service
metadata:
  name: api-lb
  labels:
    app: fiap-gerenciamento-pedidos-api-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: fiap-gerenciamento-pedidos-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080