apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: fiap-gerenciamento-pedidos-api-load-balancer
    type: LoadBalancer
spec:
  selector:
    app: fiap-gerenciamento-pedidos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
