name: pipeline
on: [push]

env:
  # Sonar
  sonar_token: ${{ secrets.SONAR_TOKEN }}

  # Github Token
  github_token: ${{ secrets.GITHUB_TOKEN }}

  # Docker Hub
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout / copy repo app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: gradle test

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout / copy repo app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Run the Gradle package task
        run: gradle app:api:build

  sonar-cloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout / copy repo app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{env.sonar_token}}
          GITHUB_TOKEN: ${{env.github_token}}
        with:
          args: >
            -Dsonar.organization=postech-fiap
            -Dsonar.projectKey=postech-fiap_fiap-gerenciamento-pedidos

  docker-app-image:
    runs-on: ubuntu-latest
    needs: sonar-cloud
    steps:
      - name: Checkout / copy repo app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login Docker Hub
        run: docker login -u ${{env.docker_username}} -p ${{env.docker_password}}

      - name: Build docker image
        run: docker build -t ${{env.docker_username}}/api-0.0.1-snapshot .

      - name: Push image docker
        run: docker push ${{env.docker_username}}/api-0.0.1-snapshot

  deploy-to-aws-eks:
    needs: docker-app-image
    if: github.ref == 'refs/heads/feature/pipeline'
    uses: ./.github/workflows/deploy-eks.yml
    secrets: inherit