name: pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Esta etapa usa a ação `actions/checkout` para fazer download de uma cópia do repositório no executor.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Esta etapa usa a configuração do java especificada
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Etapa de validação do gradle wrapper
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      # Etapa de geração do pacote do gradle
      - name: Run the Gradle package task
        run: ./gradlew build

  deploy-Stg:
    runs-on: ubuntu-latest
    environment:
      name: stg
    needs: build

    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy STG (Develop)"

  deploy-Pre:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/release'
    environment:
      name: pre
    needs: build

    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy PRE (Release)"

  deploy-Prod:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    environment:
      name: prod
    needs: build

    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy PROD (Main)"